feat:完成登录相关页面|配置mock
TDesignOteam/tdesign-miniprogram-starter pull request #10
Opened 2023-08-11 15:39 UTC by shinyina

* 完成登录相关页面 https://github.com/TDesignOteam/tdesign-miniprogram-starter/issues/9
* 配置mock

2023-08-14 06:41 UTC, shinyina commented
@LeeJim 有劳cr一下~

2023-08-24 07:29 UTC, LeeJim requested changes

2023-08-24 07:29 UTC, LeeJim commented on mock/WxMock.js
> +var __request=wx.request;var Mock=require("./mock.js");Object.defineProperty(wx,"request",{writable:true});wx.request=function(config){if(typeof Mock._mocked[config.url]=="undefined"){__request(confi
这部分代码为啥要 minify？

2023-08-24 07:29 UTC, LeeJim commented on api/request.js
> +  return new Promise(function (resolve, reject) {
这里可以直接使用箭头函数

2023-08-24 07:29 UTC, LeeJim commented on pages/login/login.less
> +.Headline {
类名不能使用驼峰写法，参考 BEM 规范

2023-08-24 09:23 UTC, shinyina commented on mock/WxMock.js
> +var __request=wx.request;var Mock=require("./mock.js");Object.defineProperty(wx,"request",{writable:true});wx.request=function(config){if(typeof Mock._mocked[config.url]=="undefined"){__request(confi
因为wxmock没有发布npm包这里是使用wxmock打包出来的文件

2023-08-24 09:23 UTC, shinyina commented on api/request.js
> +  return new Promise(function (resolve, reject) {
已修改

2023-08-24 09:23 UTC, shinyina commented on pages/login/login.less
> +.Headline {
已修改

2023-08-28 07:47 UTC, LeeJim requested changes

2023-08-28 07:47 UTC, LeeJim commented on pages/loginCode/loginCode.less
> +@--td-button-primary-disabled-color: #B5C7FF;
这个命名就很迷惑，这里应该是 less token ，却使用了 CSS Varables 语法

2023-08-28 08:01 UTC, shinyina commented on pages/loginCode/loginCode.less
> +@--td-button-primary-disabled-color: #B5C7FF;
已修改

2023-09-05 07:45 UTC, LeeJim commented
@shinyina 需要处理下冲突

2023-09-07 02:47 UTC, LeeJim approved these changes

2023-09-07 02:47 UTC, merged