feat: 完成【消息】
TDesignOteam/tdesign-miniprogram-starter pull request #11
Opened 2023-08-16 06:34 UTC by WBBB0730

### 🤔 这个 PR 的性质是？
 
- [ ] 日常 bug 修复
- [x]  新特性提交
- [ ]  文档改进
- [ ]  演示代码改进
- [ ]  组件样式/交互改进
- [ ]  CI/CD 改进
- [ ]  重构
- [ ]  代码风格优化
- [ ]  测试用例
- [ ]  分支合并
- [ ]  其他

### 🔗 相关 Issue

#4 

### 💡 需求背景和解决方案
### 📝 更新日志
feat: 完成【消息】

- [ ] 本条 PR 不需要纳入 Changelog

### ☑️ 请求合并前的自查清单
### ⚠️ 请自检并全部勾选全部选项。⚠️

- [ ] 文档已补充或无须补充
- [ ]  代码演示已提供或无须提供
- [ ]  TypeScript 定义已补充或无须补充
- [ ]  Changelog 已提供或无须提供

2023-08-28 07:38 UTC, LeeJim requested changes

2023-08-28 07:38 UTC, LeeJim commented on app.js
> +  eventBus: {
eventbus 的逻辑不要 hardcode 在 app.js

2023-08-28 07:40 UTC, WBBB0730 commented on app.js
> +  eventBus: {
那放在utils里然后在app.js中引入可以吗

2023-08-28 07:54 UTC, LeeJim commented on app.js
> +  eventBus: {
可以

2023-08-28 07:58 UTC, WBBB0730 commented on app.js
> +  eventBus: {
> 可以

已提交修改

2023-08-29 10:50 UTC, LeeJim commented
@WBBB0730 有冲突需要处理一下，另外本地跑一下 `npm run lint` 修复一下格式错误的问题

2023-08-29 13:31 UTC, WBBB0730 commented
> @WBBB0730 有冲突需要处理一下。
> 
> 另外分支需要rebase一下 main 分支，然后本地跑一下 `npm run lint` 修复一下格式错误的问题

@LeeJim  已提交修改

2023-08-30 16:43 UTC, WBBB0730 commented
@LeeJim 请问首页的目录要命名为 home 还是 index？

2023-08-31 08:41 UTC, merged