feat:发布页面开发完成
TDesignOteam/tdesign-miniprogram-starter pull request #12
Opened 2023-08-17 04:38 UTC by liangweijing

> ### 🤔 这个 PR 的性质是？
> * [ ]  日常 bug 修复
> * [x]   新特性提交
> * [ ]   文档改进
> * [ ]   演示代码改进
> * [ ]   组件样式/交互改进
> * [ ]   CI/CD 改进
> * [ ]   重构
> * [ ]   代码风格优化
> * [ ]   测试用例
> * [ ]   分支合并
> * [ ]   其他
> 
> ### 🔗 相关 Issue
> #2
> 
> ### 💡 需求背景和解决方案
> ### 📝 更新日志
> feat: 完成【消息】
> 
> * [ ]  本条 PR 不需要纳入 Changelog
> 
> ### ☑️ 请求合并前的自查清单
> ### ⚠️ 请自检并全部勾选全部选项。⚠️
> * [x]  文档已补充或无须补充
> * [x]   代码演示已提供或无须提供
> * [x]   TypeScript 定义已补充或无须补充
> * [x]   Changelog 已提供或无须提供

2023-09-05 07:30 UTC, LeeJim commented
@liangweijing 需要解决下冲突

2023-09-06 02:43 UTC, LeeJim requested changes
不要修改 eslintrc 文件，然后修复 eslint 引起的问题

2023-09-06 02:43 UTC, LeeJim commented on .eslintrc.js
> +  rules: {},
不要修改这个文件的规则 :(

2023-09-06 03:22 UTC, liangweijing commented on .eslintrc.js
> +  rules: {},
已解决，还原eslint.js文件并执行了npm run lint

2023-09-06 08:20 UTC, LeeJim approved these changes

2023-09-06 08:20 UTC, merged