feat: 完成【首页 & 目录导航】
TDesignOteam/tdesign-miniprogram-starter pull request #14
Opened 2023-08-20 08:04 UTC by Yuuki-Yuuna

2023-09-05 07:30 UTC, LeeJim commented
@Yuuki-Yuuna 需要解决下冲突

2023-09-07 04:17 UTC, Yuuki-Yuuna commented
@LeeJim 已解决，待合并

2023-09-07 09:17 UTC, LeeJim requested changes
mock 参考下 main 现有的方式

2023-09-07 09:17 UTC, LeeJim commented on app.less
> +page {
不要修改 page.less 的样式，这里是全局的样式，会影响到其他页面。
建议在各自页面修改

2023-09-07 09:17 UTC, LeeJim commented on pages/notice/index.js
> +// pages/explore/index.js
这个页面应该没有用的，需要移除掉

2023-09-13 03:19 UTC, LeeJim approved these changes

2023-09-13 03:19 UTC, merged