feat:完成【个人中心】
TDesignOteam/tdesign-miniprogram-starter pull request #19
Opened 2023-08-27 04:24 UTC by lwjlwj47

###  🤔 这个 PR 的性质是？

 - [ ] 日常bug修复
 - [x] 新特性提交
 - [ ] 文档改进
 - [ ] 演示代码改进
 - [ ] 组件样式/交互改进
 - [ ] CI/CD 改进
 - [ ] 重构'
 - [ ] 代码风格优化
 - [ ] 测试用例
 - [ ] 分支合并
 - [ ] 其他

### 🔗 相关 Issue
#5
### 💡 需求背景和解决方案

### 📝 更新日志
feat: 完成【报名人员信息维护】

 - [ ] 本条 PR 不需要纳入 Changelog

### ☑️ 请求合并前的自查清单

### ⚠️ 请自检并全部勾选全部选项。⚠️
- [x] 文档已补充或无须补充'
- [x] 代码演示已提供或无须提供
- [x] TypeScript 定义已补充或无须补充
- [x] Changelog 已提供或无须提供

2023-09-12 03:38 UTC, LeeJim requested changes

2023-09-12 03:38 UTC, LeeJim commented on pages/my/index.less
> +.loginTitle{
css 类名不要使用大小写

2023-09-12 03:38 UTC, LeeJim commented on pages/my/index.wxml
> +      wx-if='{{isLoad}}'
`wx:if` 才是正确的

2023-09-12 03:38 UTC, LeeJim commented on pages/my/index.wxml
> +      <t-icon name='file-copy' class='Release-icon'></t-icon>
不要部分使用单引号，部分使用双引号。
建议全部改成双引号

2023-09-12 04:16 UTC, lwjlwj47 commented
@LeeJim 已解决

2023-09-13 10:40 UTC, lwjlwj47 reviewed
fix:done

2023-09-14 02:48 UTC, LeeJim requested changes

2023-09-14 02:48 UTC, LeeJim commented on pages/my/index.js
> +    switch(type){
这部分 `switch ... case ... ` 的代码太冗余了，可以删了

2023-09-14 02:48 UTC, LeeJim commented on pages/my/index.json
> +  "disableScroll": true
为什么 disable scroll

2023-09-14 02:48 UTC, LeeJim commented on pages/my/index.wxml
> +    <view wx:for="{{service}}"
这部分代码使用 grid 组件来实现

2023-09-14 06:53 UTC, LeeJim requested changes

2023-09-14 06:53 UTC, LeeJim commented on pages/my/index.less
> +  height: 100vh;
为啥要限制 100vh 的高度？你切换下设备的尺寸，就能发现有些设备下是无法展示全部内容了

2023-09-14 06:53 UTC, LeeJim commented on pages/my/index.less
> +  width: 343px;
这里不要限制宽度，应该保证 margin 固定，里面的内容自动填充比较合适。你可以试试换其他尺寸的设备调试看看。

<img width="460" alt="image" src="https://github.com/TDesignOteam/tdesign-miniprogram-starter/assets/7017290/74ba57c9-23b0-46ea-8d95-7309b1987c3b">

2023-09-14 07:22 UTC, lwjlwj47 commented on pages/my/index.less
> +  width: 343px;
好的

2023-09-14 12:15 UTC, lwjlwj47 commented on pages/my/index.less
> +  width: 343px;
![176bc19e745ed5edaba851f6dee7b64](https://github.com/TDesignOteam/tdesign-miniprogram-starter/assets/82098702/de5189f5-54c1-44b1-9b26-d1562fe1e4f1)
![eff4ae1073b180a9d5d75da90462dd9](https://github.com/TDesignOteam/tdesign-miniprogram-starter/assets/82098702/dcb50870-ae66-42d5-8249-b230966f660a)
![688cc2d45b4bbd524880d0803a6c684](https://github.com/TDesignOteam/tdesign-miniprogram-starter/assets/82098702/6ce7935a-50b6-43ad-a160-a52df456585a)
![9523eabb4d4a3b26cbb10707b725556](https://github.com/TDesignOteam/tdesign-miniprogram-starter/assets/82098702/4421de69-be60-4ec4-95f2-3cbbd6f05901)

2023-09-14 12:17 UTC, lwjlwj47 commented on pages/my/index.less
> +  width: 343px;
能够适应其他尺寸的设备了

2023-09-14 12:17 UTC, lwjlwj47 commented on pages/my/index.less
> +  height: 100vh;
![1bfaf922c4f66b987262911be5fdfec](https://github.com/TDesignOteam/tdesign-miniprogram-starter/assets/82098702/a21a1a44-b13a-439f-933d-40fe18a229a1)

2023-09-14 12:17 UTC, lwjlwj47 commented on pages/my/index.less
> +  height: 100vh;
能够显示全部内容了

2023-09-15 03:20 UTC, LeeJim approved these changes

2023-09-15 03:20 UTC, merged