feat:完成【搜索】
TDesignOteam/tdesign-miniprogram-starter pull request #20
Opened 2023-09-04 05:20 UTC by Sacvengers

🤔 这个 PR 的性质是？
- [ ]  日常bug修复
- [x]  新特性提交
- [ ]  文档改进
 - [ ] 演示代码改进
 - [ ] 组件样式/交互改进
 - [ ] CI/CD 改进
- [ ]  重构'
 - [ ] 代码风格优化
 - [ ] 测试用例
 - [ ] 分支合并
 - [ ] 其他

🔗 相关 Issue  https://github.com/TDesignOteam/tdesign-miniprogram-starter/issues/3

💡 需求背景和解决方案
📝 更新日志
feat: 完成【搜索】

 本条 PR 不需要纳入 Changelog
☑️ 请求合并前的自查清单
⚠️ 请自检并全部勾选全部选项。⚠️
 文档已补充或无须补充'
 代码演示已提供或无须提供
 TypeScript 定义已补充或无须补充
 Changelog 已提供或无须提供
![5d0695f2b4e08044ef6953a2aa5cc5f](https://github.com/TDesignOteam/tdesign-miniprogram-starter/assets/96294629/2ceb16e2-ba9c-480e-b28d-c922fe3d9595)
![4ffb8c3a0dbe5a890d0447925eebc96](https://github.com/TDesignOteam/tdesign-miniprogram-starter/assets/96294629/d862ab8b-8656-43a9-9ccf-7fc04fe930c1)
![c1b56f611e7ff2de012feab4b600e2a](https://github.com/TDesignOteam/tdesign-miniprogram-starter/assets/96294629/337739de-e5c3-4d27-8016-f698acfe7246)

2023-09-07 09:22 UTC, LeeJim commented
@Sacvengers 麻烦执行一下 `npm run lint` 修复下错误

2023-09-07 09:23 UTC, Sacvengers commented
收到


---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年09月07日 17:22 |
| 收件人 | TDesignOteam/tdesign-miniprogram-starter ***@***.***> |
| 抄送人 | 廖欣茵 ***@***.***>,
Mention ***@***.***> |
| 主题 | Re: [TDesignOteam/tdesign-miniprogram-starter] feat:完成【搜索】 (PR #20) |

@Sacvengers 麻烦执行一下 npm run lint 修复下错误

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2023-09-07 15:24 UTC, Sacvengers commented
@LeeJim 老师你好，已经把npm run lint中的问题修改了，请查收！

2023-09-12 09:35 UTC, LeeJim requested changes

2023-09-12 09:35 UTC, LeeJim commented on app.json
> +    "pages/search/index"
后面缺了个 `,`

2023-09-12 09:35 UTC, LeeJim commented on pages/search/index.wxml
> +                    <t-tag class="history-item margin-12" max-width="{{343}}" variant="light">{{item;}}</t-tag>
多了一个 `;`

2023-09-12 09:35 UTC, LeeJim commented on pages/search/index.wxml
> +                           icon="search">{{item;}}
多了一个 `;`

2023-09-12 12:23 UTC, Sacvengers commented
@LeeJim 老师你好，我已经修改好，请查收！谢谢！

2023-09-13 02:27 UTC, LeeJim approved these changes

2023-09-13 02:27 UTC, merged