feat:完成【数据图表页】和【设置页】
TDesignOteam/tdesign-miniprogram-starter pull request #21
Opened 2023-09-10 07:20 UTC by chendingya

🤔 这个 PR 的性质是？

 新特性提交

🔗 相关 Issue 
https://github.com/TDesignOteam/tdesign-miniprogram-starter/issues/8
https://github.com/TDesignOteam/tdesign-miniprogram-starter/issues/7

💡 需求背景和解决方案
📝 更新日志
feat:完成【数据图表页】和【设置页】
![{DEE01215-636A-4065-B912-BD0E4B2FC750}](https://github.com/TDesignOteam/tdesign-miniprogram-starter/assets/91456388/c32abce9-6237-4f06-a36f-7d12541e70d6)

![QQ截图20230910143736](https://github.com/TDesignOteam/tdesign-miniprogram-starter/assets/91456388/e77b5e35-d93e-4c2a-b7aa-99ff263649fc)
![QQ截图20230910143804](https://github.com/TDesignOteam/tdesign-miniprogram-starter/assets/91456388/4d5bc03c-32b1-482e-a932-acba6fdbabbe)

2023-09-12 09:38 UTC, LeeJim requested changes
`.idea` 这个目录不要上传上来

2023-09-13 05:00 UTC, chendingya commented
> 

已删除

2023-09-13 09:15 UTC, LeeJim commented
<img width="1084" alt="image" src="https://github.com/TDesignOteam/tdesign-miniprogram-starter/assets/7017290/c6415291-ce5c-4945-a812-2a335faeb22f">

没有数据

2023-09-13 14:28 UTC, chendingya commented
> <img alt="image" width="1084" src="https://user-images.githubusercontent.com/7017290/267601063-c6415291-ce5c-4945-a812-2a335faeb22f.png">
> 没有数据

因为不清楚mock要以什么形式，所以我把数据放在dataCenter文件夹中的mock.config.json，需要导入到微信开发者工具的mock
![image](https://github.com/TDesignOteam/tdesign-miniprogram-starter/assets/91456388/476ee45b-bf9b-4004-ab8f-ea4199e8963f)

2023-09-14 02:35 UTC, LeeJim commented
根目录有个mock文件，可以参考那个方式

2023-09-15 04:32 UTC, closed without merging