feat: 增加跳转功能 && 抽象三个tabbar的topbar为公共组件
TDesignOteam/tdesign-miniprogram-starter pull request #24
Opened 2023-09-15 13:13 UTC by Runtus

🤔 这个 PR 的性质是？
 - [ ] 日常bug修复
 - [ ] 新特性提交
 - [ ] 文档改进
 - [ ] 演示代码改进
 - [x] 组件样式/交互改进
 - [ ] CI/CD 改进
 - [ ] 重构
 - [ ] 代码风格优化
 - [ ] 测试用例
 - [ ] 分支合并
 - [ ] 其他

* 增加页面间跳转功能，同时将nav抽象为公共组件。

2023-09-19 03:35 UTC, LeeJim requested changes
components 可以和 pages 同级

2023-09-19 04:17 UTC, Runtus commented
已将components移至pages同级

2023-09-19 09:00 UTC, LeeJim requested changes

2023-09-19 09:00 UTC, LeeJim commented on pages/home/index.wxml
> +  <nav nav-type="search" />
这个 nav-type 应该是没有用的了吧

2023-09-19 09:00 UTC, LeeJim commented on pages/home/index.wxml
> +<!-- 子组件直接进行跳转会有相对路径问题，这里提升至父组件进行 -->
这个问题应该也不存在了吧？

2023-09-19 09:02 UTC, Runtus commented on pages/home/index.wxml
> +<!-- 子组件直接进行跳转会有相对路径问题，这里提升至父组件进行 -->
噢噢对，抱歉，我把这注释改一下

2023-09-19 09:18 UTC, Runtus commented on pages/home/index.wxml
> +  <nav nav-type="search" />
nav-type用于区分nav的用途，我一开始想用slot来实现这一块儿组件的抽象的，但是外部的slot放在tdesign的t-navbar的slot里没有生效，所以我就以props的形式来区分search还是title

2023-09-20 07:46 UTC, LeeJim approved these changes

2023-09-20 07:46 UTC, merged